### ISSUE TITLE
``setup.py build`` tries to modify the site-packages

### ISSUE THREAD

**Issue by truh** [bryancatanzaro/copperhead#16]
I was trying to build copperhead as part of an [AUR](https://wiki.archlinux.org/index.php/Arch_User_Repository) package build. The packages are first compiled with normal privileges and after the package got assemble it is installed to the system with superuser privileges.

Here is my problem. It seems to me like the setup script tries to modify the site-packages of the global python installation. This obviously fails because it would require higher privileges.  

``` python
[jakob@manj copperhead]$ python2 setup.py build
Scanning installed packages
Setuptools installation detected at /usr/lib/python2.7/site-packages
Non-egg installation
Removing elements out of the way...
Renaming /usr/lib/python2.7/site-packages/setuptools-15.0-py2.7.egg-info into /usr/lib/python2.7/site-packages/setuptools-15.0-py2.7.egg-info.OLD.1429037986.46
Creating /tmp/copperhead/setuptools-0.6c9-py2.7.egg-info
Creating /tmp/copperhead/setuptools.pth
Traceback (most recent call last):
  File "setup.py", line 21, in <module>
    use_setuptools()
  File "/tmp/copperhead/distribute_setup.py", line 136, in use_setuptools
    fake_setuptools()
  File "/tmp/copperhead/distribute_setup.py", line 365, in fake_setuptools
    res = _remove_flat_installation(setuptools_location)
  File "/tmp/copperhead/distribute_setup.py", line 248, in _remove_flat_installation
    patched = _patch_egg_dir(pkg_info)
  File "/tmp/copperhead/distribute_setup.py", line 303, in _patch_egg_dir
    _rename_path(path)
  File "/tmp/copperhead/distribute_setup.py", line 228, in _rename_path
    os.rename(path, new_name)
OSError: [Errno 13] Permission denied
```

I talked to the packages maintainer here:
https://aur.archlinux.org/packages/copperhead-hg/

The maintainer is migrating to the new github repo here:
https://aur.archlinux.org/packages/python2-copperhead-git/

**Comment by truh** [comment]
I doubt it's still relevant after 10 years
