### ISSUE TITLE
Array cannot be safely cast to required type.

### ISSUE THREAD

**Issue by adammathys** [bryancatanzaro/copperhead#2]
Under Ubuntu 11.10, Copperhead runs into issues with Numpy v1.6.1. The following traceback occurs when trying to run the axpy.py sample:

```
Traceback (most recent call last):
 File "samples/axpy.py", line 57, in<module>
   (x, y, z, zPython, error) = test_saxpy(length)
 File "samples/axpy.py", line 41, in test_saxpy
   z = axpy(a, x, y)
 File "/home/adamm/.virtualenvs/copper/local/lib/python2.7/site-packages/copperhead-0.2a2-py2.7.egg/copperhead/runtime/cufunction.py", line 58, in __call__
   return P.execute(self, args, kwargs)
 File "/home/adamm/.virtualenvs/copper/local/lib/python2.7/site-packages/copperhead-0.2a2-py2.7.egg/copperhead/runtime/driver.py", line 47, in execute
   return execute(self.tag(), cufn, *args, **kwargs)
 File "/home/adamm/.virtualenvs/copper/local/lib/python2.7/site-packages/copperhead-0.2a2-py2.7.egg/copperhead/runtime/driver.py", line 107, in execute
   cu_types, cu_inputs = zip(*map(induct, v))
 File "/home/adamm/.virtualenvs/copper/local/lib/python2.7/site-packages/copperhead-0.2a2-py2.7.egg/copperhead/runtime/driver.py", line 76, in induct
   induced = cudata.cuarray(x)
TypeError: array cannot be safely cast to required type
```

A similar error occurs for 78 of the tests as well. Reverting to Numpy v1.5.1 corrects the issue.

**Comment by bryancatanzaro** [comment]
I think this issue is fixed with newer versions of Copperhead.  At least on my Ubuntu 12.04 machine with Numpy 1.6.1, as well as on my OS X 10.7.4 machine, numpy 1.6.1 works.  Let me know if it's still a problem on your setup.

**Comment by adammathys** [comment]
Confirmed woking using the most recent version of Copperhead.
